import OpenAI from "openai";

if (!process.env.OPENAI_API_KEY) {
  throw new Error("OPENAI_API_KEY environment variable is required");
}

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

interface MessageContext {
  previousMessages: Array<{
    role: 'user' | 'assistant';
    content: string;
  }>;
  contactInfo?: {
    name?: string;
    company?: string;
    jobTitle?: string;
  };
}

// Mock suggestions for testing when API fails
const getMockSuggestions = (message: string, context: MessageContext): string[] => {
  const name = context.contactInfo?.name || 'there';
  return [
    `Hi ${name}, thank you for your message. I'd be happy to help you with that.`,
    `Hello ${name}, I appreciate you reaching out. Let me assist you with your request.`,
    `Thank you for contacting us, ${name}. I understand what you're looking for.`
  ];
};

export async function generateResponseSuggestions(
  latestMessage: string,
  context: MessageContext
): Promise<string[]> {
  try {
    const systemPrompt = `You are an AI assistant helping generate professional response suggestions for a CRM platform.
    Keep responses concise, professional, and contextually appropriate.
    Consider the contact's information and conversation history when generating suggestions.`;

    const messages = [
      { role: "system", content: systemPrompt },
      ...context.previousMessages,
      { role: "user", content: `Generate 3 different professional responses to this message: "${latestMessage}"
        ${context.contactInfo ? `\nContact Info: ${JSON.stringify(context.contactInfo)}` : ''}
        \nFormat responses as a numbered list.` }
    ] as OpenAI.Chat.ChatCompletionMessageParam[];

    const response = await openai.chat.completions.create({
      model: "gpt-3.5-turbo",
      messages,
      temperature: 0.7,
      max_tokens: 150,
      n: 1,
    });

    const suggestions = response.choices[0].message?.content
      ?.split('\n')
      .filter(line => line.trim().match(/^\d+\./))
      .map(line => line.replace(/^\d+\.\s*/, '').trim()) || [];

    if (suggestions.length === 0) {
      console.log('No suggestions generated by OpenAI, using mock suggestions');
      return getMockSuggestions(latestMessage, context);
    }

    return suggestions;
  } catch (error) {
    console.error('Error generating suggestions:', error);
    console.log('Using mock suggestions due to API error');
    return getMockSuggestions(latestMessage, context);
  }
}